language: objective-c
osx_image: xcode9.2
xcode_workspace: ShopApp.xcworkspace
xcode_scheme: ShopApp

before_install:
  - pod repo update

cache:
  - bundler
  - cocoapods

notifications:
  slack:
    rooms:
      - shopclientapp:EBh1k4fcosP8EYhbD1R0S2qm#ios
  email: false
  
branches:
  only:
    - master
    - develop

script:
  - xcodebuild -workspace ShopApp.xcworkspace -scheme ShopApp -configuration 'Debug' -sdk 'iphonesimulator11.2' -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
